### ISSUE TITLE
Customize the languages' list

### ISSUE THREAD

**Issue by antleblanc** [ovh-ux/component-rollup-config#60]
**Is your feature request related to a problem? Please describe.**
I'm wondering how I can configure a custom list of languages.

ref: https://github.com/ovh-ux/component-rollup-config/blob/master/src/plugins/translation-utils.js#L6-L25

**Comment by Jisay** [comment]
Yes as a potential user of the library I should be abble to customize the language list because I manage some other languages than the list provided by @antleblanc.

And also for our needs: there should not be the same locales for the European manager and the Canadian manager for example.

**Comment by frenautvh** [comment]
@Jisay pull request https://github.com/ovh-ux/component-rollup-config/pull/72 might solve your issue
